### ISSUE TITLE
Create an SAP Fiori App Using SAP Business Application Studio

### ISSUE THREAD

**Issue by EkaterinaArena** [sap-tutorials/Tutorials#18282] opened 2022-03-31 08:37 UTC
Tutorials: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html
--------------------------
Hi Colleagues,

I am following the tutorial.
At the step 3, point 3:  "A new browser tab opens showing the app. In this stage of the development, the app only shows a title."
Actual result:
-  a new browser window is opened as expected
-  However, sign-in form is displayed (please, see attached image)
   Sign in
   https://port8080-workspaces-ws-blgkw.ap21.trial.applicationstudio.cloud.sap
   Username
   Password

![BAS_Fiori_tutorial](https://user-images.githubusercontent.com/26485662/161012907-a1794061-1352-4098-997e-0b99c4e373af.JPG)
.

On my side I have tried credentials for BTP, ES5. Also, on 30/03/2022 it was not observed.

Could you please help with it? It is planned to used for the customer demo.

thank you and regards
Ekaterina

**Comment by raz-korn** [comment] 2022-04-02 14:00
Hi @EkaterinaArena ,

This needs some investigation.
I hope to have answer early next week or a workaround.

Regards - Raz

**Comment by ianquigley-sap** [comment] 2022-04-04 10:39
Hi @EkaterinaArena,

Can you please confirm you are using the right credentials?  You should be able to login to ES5 directly at: https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui?sap-client=002&sap-language=EN#

You can reset your password if needed at: https://register.sapdevcenter.com/SUPSignForms.  You should wait for an email which will have a temp password, then please reset it using this link https://sapes5.sapdevcenter.com/sap/bc/gui/sap/its/webgui#

Regards,
Ian

**Comment by raz-korn** [comment] 2022-04-07 05:41
Hi @EkaterinaArena ,

On our end we are unable to reproduce it.
Does this still happen?
If it does, contact me directly, and we'll look into this online.

Regards - Raz

**Comment by EkaterinaArena** [comment] 2022-04-07 09:05
Hello Raz,
thank you for verification and reply!
ES5 credentials were correct.
I have just re-done the tutorial again and this time it has passed. I think it was trial env issues last week.

The only little comment I have is related to  the last step:
https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html
Step 4: Access the application on SAP BTP, Cloud Foundry environment
point 5 (running cf html5-list -di FioriDemo-dest-srv -u -rt launchpad)
> Press [CTRL] and click the app’s link in the terminal.

Actual result: 
- I have tril env session opened in one of the tab in the browser (chrome)
-  i open the link as-is from the BAS terminal command
- > The new browser tab is opened with "Internal Server Error" message.
However, if I open the app from BTP cockpit > HTML5 Applications - it is working correctly.

thank you and regards
Ekaterina

**Comment by MichaelCzcz** [comment] 2022-05-18 06:45
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2022-05-18 06:45 UTC
