### ISSUE TITLE
Create an ABAP Database Table and Relevant ABAP Dictionary Objects

### ISSUE THREAD

**Issue by james16888** [sap-tutorials/Tutorials#18667] opened 2022-07-29 07:46 UTC
Tutorials: https://developers.sap.com/tutorials/abap-dev-create-table.html
--------------------------

when I answer the test yourself question, all the 3 answer options are not correct. So I can't finish this tutorial. Please check and udpate.

**Comment by julieplummer20** [comment] 2022-10-06 08:18
Hi James, 
Strange. The second answer is correct. I have *just* tested this and get a success message, "Correct!"
It appears that the issue is not on the server side. 
I will investigate. In the meantime, can you please try deleting your browser cache?
Thanks and best wishes,
Julie.

**Comment by julieplummer20** [comment] 2023-02-13 12:38
Hi james16888, Is this still an issue? If so, please just let me know at once. 
If not, I will close this issue. 
Thanks and best wishes,
Julie.

**Closed** 2023-03-28 08:09 UTC
