### ISSUE TITLE
Install SAP Intelligent RPA On-Premise Components

### ISSUE THREAD

**Issue by ihorivaniii** [sap-tutorials/Tutorials#7357] opened 2021-12-28 11:42 UTC
Tutorials: https://developers.sap.com/tutorials/irpa-setup-2-onpremise-installation.html
--------------------------
Step 8: has no button done and I can't finish it
![image](https://user-images.githubusercontent.com/45239748/147562759-dd827cec-4b26-4be8-97bb-3d4928522ea0.png)

Write here how you think we can improve the tutorial ...

**Comment by iwonahahn** [comment] 2022-01-04 16:51
Hi @ihorivaniii,

The issue is fixed now and you should see the Done button now.

![2022-01-04_17-51-02](https://user-images.githubusercontent.com/22098308/148094301-868b4300-e7c8-4fe3-b0e8-4ba543c69289.png)

Best regards,
Iwona

**Closed by iwonahahn** 2022-01-04 16:51 UTC
