### ISSUE TITLE
"Technical Error" / HTTP 500 when submitting quiz answers in tutorial steps

### ISSUE THREAD

**Issue by chrisma** [sap-tutorials/Tutorials#23000] opened 2023-04-19 08:29 UTC
Tutorials: https://developers.sap.com/tutorials/cp-explore-cloud-platform.html

--------------------------

* Tutorial: View the SAP BTP from 10,000 Meters
* Step: STEP 2 What does "as a Service" mean?
* Action: Selecting quiz answers and submitting them via "Check answer" button
* Behavior: Display of "Technical Error" (due to HTTP 500 after POST to `/developers.sap.com/bin/sapdx/tutorials/forms/validate`)
* Expected behavior: Visual feedback on quiz answers
* Additional notes: Check for correct answers could potentially use client-side JS as answers are described in the next step anyways. 
* Browser: Google Chrome Version 112.0.5615.49 (Official Build) (x86_64), Safari Version 16.3 (18614.4.6.1.6)

![SCR-20230419-ivqd](https://user-images.githubusercontent.com/1652117/233016377-1b42ea53-cb50-4549-9d29-4368d449eda3.png)

**Comment by chrisma** [comment] 2023-04-19 09:10
This seems to be an issue with multiple (all?) quizzes

![image](https://user-images.githubusercontent.com/1652117/233027146-8b264cb1-2056-4260-b5b7-210bbacf6700.png)

**Comment by qmacro** [comment] 2024-07-26 15:02
Hey @jmmargo I'm not sure why this is assigned to me - can you please clarify? Thanks!

**Comment by jmmargo** [comment] 2024-07-26 15:29
Christoph, I am unable to reproduce the errors that you have reported.  There might have been a glitch on the day you were testing, but they all seem to work as expected.  I am sorry for the delay in responding to this issue.  Please reopen this if you are still having an issue.

**Closed by jmmargo** 2024-07-26 15:29 UTC
