### ISSUE TITLE
Details of the deployed application and its URL not getting displayed when executing the command in the terminal

### ISSUE THREAD

**Issue by BaskarThambiayah** [sap-tutorials/Tutorials#23160] opened 2023-08-13 19:05 UTC
Tutorial: https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html

Hi Colleagues,
While executing "Step **4 Access the application on SAP BTP, Cloud Foundry environment**" of this tutorial, when I enter the command **cf html5-list -di FioriDemo-destination-service -u -rt launchpad** in the terminal to get the details of the deployed application and its URL, it is not fetching any values.

Actual Result in the UI:
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/f9ce2d12-91fe-4af2-9eea-b54cda49a818)

Expected Result :
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/2a271c0e-fbff-407a-a681-c7f670f2a600)

Labels to be added:
Scenario label: SCPTest-fbizapp
Sprint Label: SCPTest-2308A
Landscape Label: Trial3 (AP Region)
Priority: High

Many thanks & regards,
Baskar

**Comment by birgits22** [comment] 2023-08-21 08:16
Hi Baskar,
I tested this as well. For me it worked without any issues. Could you please re-test, if it works for you now? If not, can we please sync? Might be you are missing some entitlements.
Many thanks,
Birgit

**Comment by BaskarThambiayah** [comment] 2023-09-15 15:41
Hi Birgit, 
I tried to execute this scenario multiple times in different new accounts in AP Region by following the tutorial. 
But the issue remains. Kindly check this issue.

Many thanks & regards,
Baskar

**Comment by birgits22** [comment] 2023-09-15 16:35
Hi Baskar,

Many thanks for following up. Could you please send me some further information like screenshots, log files, debugging information? Unfortunately I can’t reproduce the issue. 😢
Might be this is also caused by missing BTP entitlements. Could you please send me a screenshot of your entitlements?

Many thanks,
Birgit

Von meinem iPhone gesendet

Am 15.09.2023 um 17:41 schrieb BaskarThambiayah ***@***.***>:

﻿

Hi Birgit,
I tried to execute this scenario multiple times in different new accounts in AP Region by following the tutorial.
But the issue remains. Kindly check this issue.

Many thanks & regards,
Baskar

**Comment by BaskarThambiayah** [comment] 2023-09-16 06:36
Hi Birgit,
Thank you so much for your swift response. 

cf deploy mta_archives/FioriDemo_0.0.1.mtar was successful and the required services and the relevant keys have got created successfully.

Service key "FioriDemo-repo-host-key" for service "FioriDemo-html5-srv" 
Service key "FioriDemo-uaa-key" for service "FioriDemo-xsuaa-srv"
Service key "FioriDemo-dest-content-FioriDemo-destination-service-credentials" for service "FioriDemo-destination-service"

Please find the screenshots attached herewith for your reference.

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/74131a58-93d8-4edd-b3ec-d9824364666d)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/a745f862-e2ee-4da6-8cc8-60dfb13c3093)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/4fa712ef-981e-4ff6-8d45-ab4495bc7474)

But while executing the following command in the terminal to get the details of the deployed application and its URL to access the application on SAP BTP, Cloud Foundry environment, it is not loading the details of the deployed application and its URL. 
Instead, we are getting the below screen.
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/f892f7bf-0adb-4059-8b9b-ca097988c30c)

Please find the screenshots of entitlement below.
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/787f0809-93ea-4f7b-9623-f6a0e78996b0)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/f54afb46-6cb1-40e3-8bfa-e3dec3b0229f)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/62780913-3429-4534-a8c6-358c77104fb2)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/2b6a98f4-ff51-4fb0-8892-48dfdae993e5)

I have also given access your user birgit.selbach@sap.com in my subaccount.
https://account.hanatrial.ondemand.com/trial/#/globalaccount/ba7a5e5e-0f30-4cb8-bdc7-5630f2c0777d/subaccount/0ae3c8a6-083c-426d-b0b3-1049d3f7bc92/subaccountoverview

Many thanks & regards,
Baskar

**Comment by birgits22** [comment] 2023-09-20 09:38
Hi Baskar,

Thanks for adding me to your account. Unfortunately I can’t access the same dev space as you. But at least I can check for the entitlements 😊

When trying to do so I realized my trial account got deleted. Thus I started with a new one. Here are some observations I made. Perhaps this can help to solve your issue. If so I would update the tutorial accordingly.

In my Singapore Subaccount I found the following:

In tutorial Build and Deploy Your SAP Fiori App to SAP Business Technology Platform | SAP Tutorials<https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html>
In step2 4 I found I have several subaccounts and had to choose the correct one. (I can add a note that leaners need to make sure to choose the correct one.)

***@***.***

With this I was able to execute all steps as described in the tutorial. Then I compared your HTML5 Applications entry in the trial subaccount: It seems your app was deployed to somewhere else – at least I can’t find it under he HTML5 applications. Here is how this should look like:

***@***.***

In your case it shows an error

***@***.***

Please check this question: Destination points to the html5-apps-repo instance, which does not contain any HTML5 applications | SAP Community<https://answers.sap.com/questions/13620104/destination-points-to-the-html5-apps-repo-instance.html> Perhaps it answers your question.

I will now try with a US account. How did you proceed for thisß Did you create a new global account in trial or did you create a new subaccount under your trial account?

Many thanks,
Birgit

**Comment by birgits22** [comment] 2023-09-20 12:57
Hi Baskar,

I now also tested it in a US subaccount. I manually created this as a subaccount. If someone uses the default trail account, which is auto created those issues should not appear.

A couple of things, which I noticed we should add:
Cloud Foundry is not enabled by default and a dev space is needed (I will add a remark that this might need to be done.)
The SAP Business Application Studio entitlement needs to be added. Only then it is possible to find it in the service market place. (I will add a remark to the tutorial.)
Same for SAP Build workzone.

In this case I was able to reproduce your issue – it can be resolved by adding the following service plan (under entitlements):
Authorization and Trust Management Service (technical name XSuaa) This should look as follows:

***@***.***

After adding the service plan I was able to proceed.

I will add a remark in github to try to add the missing service plan I was able to deploy the mtar.

Please let me know, if this helps for you as well.

Many thanks,
Birgit

From: Selbach, Birgit
Sent: Wednesday, 20 September 2023 11:39
To: sap-tutorials/Tutorials ***@***.***>; Thambiayah, Baskar ***@***.***>
Subject: RE: [sap-tutorials/Tutorials] Details of the deployed application and its URL not getting displayed when executing the command in the terminal (Issue #23160)

Hi Baskar,

Thanks for adding me to your account. Unfortunately I can’t access the same dev space as you. But at least I can check for the entitlements 😊

When trying to do so I realized my trial account got deleted. Thus I started with a new one. Here are some observations I made. Perhaps this can help to solve your issue. If so I would update the tutorial accordingly.

In my Singapore Subaccount I found the following:

In tutorial Build and Deploy Your SAP Fiori App to SAP Business Technology Platform | SAP Tutorials<https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html>
In step2 4 I found I have several subaccounts and had to choose the correct one. (I can add a note that leaners need to make sure to choose the correct one.)

***@***.***

With this I was able to execute all steps as described in the tutorial. Then I compared your HTML5 Applications entry in the trial subaccount: It seems your app was deployed to somewhere else – at least I can’t find it under he HTML5 applications. Here is how this should look like:

***@***.***

In your case it shows an error

***@***.***

Please check this question: Destination points to the html5-apps-repo instance, which does not contain any HTML5 applications | SAP Community<https://answers.sap.com/questions/13620104/destination-points-to-the-html5-apps-repo-instance.html> Perhaps it answers your question.

I will now try with a US account. How did you proceed for thisß Did you create a new global account in trial or did you create a new subaccount under your trial account?

Many thanks,
Birgit

**Comment by birgits22** [comment] 2023-09-26 10:57
Hi Baskar,

Before this gets lost: did you have a chance to try this out?

Many thanks,
Birgit

From: Selbach, Birgit
Sent: Wednesday, 20 September 2023 14:57
To: 'sap-tutorials/Tutorials' ***@***.***>; Thambiayah, Baskar ***@***.***>
Subject: RE: [sap-tutorials/Tutorials] Details of the deployed application and its URL not getting displayed when executing the command in the terminal (Issue #23160)

Hi Baskar,

I now also tested it in a US subaccount. I manually created this as a subaccount. If someone uses the default trail account, which is auto created those issues should not appear.

A couple of things, which I noticed we should add:
Cloud Foundry is not enabled by default and a dev space is needed (I will add a remark that this might need to be done.)
The SAP Business Application Studio entitlement needs to be added. Only then it is possible to find it in the service market place. (I will add a remark to the tutorial.)
Same for SAP Build workzone.

In this case I was able to reproduce your issue – it can be resolved by adding the following service plan (under entitlements):
Authorization and Trust Management Service (technical name XSuaa) This should look as follows:

***@***.***

After adding the service plan I was able to proceed.

I will add a remark in github to try to add the missing service plan I was able to deploy the mtar.

Please let me know, if this helps for you as well.

Many thanks,
Birgit

From: Selbach, Birgit
Sent: Wednesday, 20 September 2023 11:39
To: sap-tutorials/Tutorials ***@***.******@***.***>>; Thambiayah, Baskar ***@***.******@***.***>>
Subject: RE: [sap-tutorials/Tutorials] Details of the deployed application and its URL not getting displayed when executing the command in the terminal (Issue #23160)

Hi Baskar,

Thanks for adding me to your account. Unfortunately I can’t access the same dev space as you. But at least I can check for the entitlements 😊

When trying to do so I realized my trial account got deleted. Thus I started with a new one. Here are some observations I made. Perhaps this can help to solve your issue. If so I would update the tutorial accordingly.

In my Singapore Subaccount I found the following:

In tutorial Build and Deploy Your SAP Fiori App to SAP Business Technology Platform | SAP Tutorials<https://developers.sap.com/tutorials/appstudio-fioriapps-mta-build-deploy.html>
In step2 4 I found I have several subaccounts and had to choose the correct one. (I can add a note that leaners need to make sure to choose the correct one.)

***@***.***

With this I was able to execute all steps as described in the tutorial. Then I compared your HTML5 Applications entry in the trial subaccount: It seems your app was deployed to somewhere else – at least I can’t find it under he HTML5 applications. Here is how this should look like:

***@***.***

In your case it shows an error

***@***.***

Please check this question: Destination points to the html5-apps-repo instance, which does not contain any HTML5 applications | SAP Community<https://answers.sap.com/questions/13620104/destination-points-to-the-html5-apps-repo-instance.html> Perhaps it answers your question.

I will now try with a US account. How did you proceed for thisß Did you create a new global account in trial or did you create a new subaccount under your trial account?

Many thanks,
Birgit

**Comment by BaskarThambiayah** [comment] 2023-10-05 07:06
Hi Birgit,
I tried creating a new Glabal Trial Account -> Subaccount in AP region again and verified that all the required entitlement are in place. Then, tried this scenario execution. But I am getting the same issue in AP Region. Deployment is passed but the cf command  "html5-list -di FioriDemo-destination-service -u -rt launchpad" in the terminal doesn't return any value. 
I get the same error again in HTML5 Applications page.
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/e0f696e0-9ea6-4c31-b34b-58199456f6b4)

And i have only one subaccount in which i deployed the mtar file. During the deployment, it has created "Destination Service", "HTML5 Application Repository Service" and "Authorization and Trust Management Service" and the relevant service keys successfully. 
But i don't know why i get the error in HTML5 Applications page in AP Region only.

I tried adding the Code-Snippet mentioned in the link "https://answers.sap.com/questions/13620104/destination-points-to-the-html5-apps-repo-instance.html" at the end of manifest.json. But sap.cloud is not available.
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/ecd39e6b-aa7e-432e-a97e-a78ff153dc84)

Kindly check this issue.

Many thanks & regards,
Baskar

**Comment by birgits22** [comment] 2023-10-09 12:33
Hi Baskar,

Many thanks for your feedback. This seems not to be related to SAP Business Application Studio, but to something in BTP. Could you please open a support ticket for this issue?

Best regards,
Birgit

**Comment by BaskarThambiayah** [comment] 2023-10-15 14:12
Hi Birgit,
Many thanks for the feedback.
I compared this scenario execution in US and AP regions.
Below are my observations in US and AP Regions after the deployment of FioriDemo_0.0.1.mtar file.

In US Region:
3 Service Instances got created.
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/470b1e90-265e-4473-a443-838224947b53)

Generated Key for each Service Instance in US Region:
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/6796861c-4283-4c1b-be7e-18b8ba6fc403)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/6cb66690-d37b-4eb2-8892-30de50067b45)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/0ccfaefe-7c79-476d-af7f-2f6dc9fa0932)

Deployed Application in HTML5 Applications:
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/fbc4b242-b21f-4a43-a037-bf3b7001aaee)

In AP Region:

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/e4b5d51e-2a13-466e-b23b-2e2098282510)

5 Service Instances got created. (2 extra with name undefined-destination-service and undefined-html5-srv)
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/3a5dce40-3568-4b7e-9866-e0bc0532d604)

Generated Key for each Service Instance in AP Region:
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/b48321c7-8e55-48d4-a009-0fc2e392da41)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/73a8a2d9-3a5f-47c1-896b-a8083a412c35)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/826c3f89-c4a7-431b-a2c2-76726df8e63e)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/973fd05b-b987-4a7d-b745-e9c29189ebab)

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/4aa54dfb-03e9-47bb-baf0-e84eab5c27a1)

Deployed Application in HTML5 Applications:
This page is showing configuration issue.
![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/966fee3e-f972-4318-a247-d8610877b2b3)

Also i have observed that in AP Region, it is adding only 61 entitlements. But in US region, there are 72 entitlements got added while creating the subaccount. So i tried to add the missing entitlements in AP Region, but i am getting the error as "This service is not available for new assignments in this subaccount's region."

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/00a8c272-b0a0-493a-ab0d-17568e9f4395)

Below entitlements are missing in AP region.
Business Entity Recognition Trial
Continuous Integration & Delivery
Data Attribute Recommendation
Document Information Extraction Trial
Document Translation
Master Data Integration
Personal Data Manager
PostgreSQL, Hyperscaler Option
SAP Build Apps
SAP Build Process Automation
SAP Graph
SAP Hana Cloud
SAP HANA Schemas & HDI Containers Trial
Service Ticket Intelligence Trial

So i am not sure if this could be the reason for the failure of this scenario execution in AP region.
If you still feel that i want to create a support ticket, please share me the component so that i will create a ticket.

Many thanks & regards,
Baskar

**Comment by BaskarThambiayah** [comment] 2023-11-29 06:58
Hi Birgit,
Many thanks for the BCP Component detail. I have raised the BCP Ticket https://support.wdf.sap.corp/sap/support/message/2380141151 against the mentioned component now.

Kind regards,
Baskar

**Comment by BaskarThambiayah** [comment] 2024-01-12 11:50
Hi Birgit,
Update: During the validation of this scenario in Jan'24 month, we are facing the same issue in US region as well. Until last month cycle, this scenario was working fine in US region, we faced this issue in AP region only. Now, this issue is occuring in both AP and US Regions.

![image](https://github.com/sap-tutorials/Tutorials/assets/60343237/da08262d-4ea5-4328-8218-6d7f0b872c5d)

Kind regards,
Baskar

**Closed** 2024-06-13 01:54 UTC
Labels: SCPTest-trial2, SCPTest-fbizapp, SCPTest-trial3, High-Prio, SCPTest-2308A, SCPTest-2309A, SCPTest-2310A, SCPTest-2311A, SCPTest-2312A, SCPTest-2401A, SCPTest-2402A, SCPTest-2403A, SCPTest-2404A
