### ISSUE TITLE
Expose Integration Flow Endpoint as API and Test the Flow

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/Tutorials#23725] opened 2024-09-11 06:00 UTC
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-api-management.html
--------------------------

Hello,

I think in the Step 6 Congratulations! the formatting should not be for code:

![image](https://github.com/user-attachments/assets/a686e92f-4c39-440d-990e-4b707a0eca59)

Best Regards
Gregor

**Comment by Karunaharan** [comment] 2024-09-16 07:02
Hi @gregorwolf,
Thanks for noticing this.
The issue is fixed now. You can see the changes in a day or two's time.

**Closed by Karunaharan** 2024-09-16 07:02 UTC
