### ISSUE TITLE
Set Up Computer Vision Package for SAP AI Core

### ISSUE THREAD

**Issue by YoheiFukuhara** [sap-tutorials/Tutorials#18700] opened 2022-08-09 09:01 UTC
Tutorials: https://developers.sap.com/tutorials/cv-package-aicore-setup.html
--------------------------

Write here how you think we can improve the tutorial ...
There are 3 issues on the tutorial.
1.  "pip install torch==1.10 torchvision" doesn't work at step4.
 due to package dependency, I managed with torchvision==0.11.1
2. incorrect python script at step 13

```python: wrong
ai_api_client = AIAPIV2Client(
    base_url = aic_service_key["serviceurls"]["AI_API_URL"] + "/v2/lm", # The present AI API version is 2
    auth_url=  aic_service_key["url"] + "/oauth/token",
    client_id = aic_service_key['clientid'],
    client_secret = aic_service_key['clientsecret']
)
```

The above code should be the below one.

```python: correct
ai_api_client = AICoreV2Client(
    base_url = aic_service_key["serviceurls"]["AI_API_URL"] + "/v2", # The present AI API version is 2
    auth_url=  aic_service_key["url"] + "/oauth/token",
    client_id = aic_service_key['clientid'],
    client_secret = aic_service_key['clientsecret']
)
```

**Comment by kannankumar** [comment] 2022-08-25 13:50
Hi @YoheiFukuhara,
thanks for reporting the bugs.

Point 1: Did you face any errors during installation with the command provided in the tutorial? 
`torchvision` has no strict version requirements as seen in the pip command you shared. `torchvision==0.11.1` is the version that gets installed with `pytorch==1.10.0` as of now. That should be ok.  Is there any change required in the tutorial?

Point 2: has been fixed with PR #18741.

**Comment by YoheiFukuhara** [comment] 2022-08-29 07:26
Hi @kannankumar 
> Point 1: Did you face any errors during installation with the command provided in the tutorial?
Yes, I did.  Though I didn't keep my logs at that time, I remember the pip installation failure with `pip install torch==1.10 torchvision`.
If you succeed with `pip install torch==1.10 torchvision`, then how about adding my solution as a remark?

**Comment by kannankumar** [comment] 2022-08-29 07:33
Yea sure we can surely add your solution as a remark if that is missing. 
Could you share what was your solution? what command(s) did you execute?
Also would be helpful to give some details :
- OS
- Python version
- torch version

We would like to understand the details so we can find and solve the root cause of the problem, if it is something other than torchvision package dependency.
Thanks.

**Comment by YoheiFukuhara** [comment] 2022-08-29 07:55
I deleted my environments, since it was on cloud.
I used GCE on Google Cloud.
So the below information may be incorrect.

- OS: Debian
- Python: 3.9.13
- torch: 1.10

I executed `pip install torch==1.10 torchvision==0.11.1`.

**Comment by MichaelCzcz** [comment] 2023-02-21 08:01
@kannankumar Any updates? Please close this issue if it has been resolved.

**Comment by jmmargo** [comment] 2024-08-12 21:22
As there have been no updates, I am assuming this issue is closed.  Please reopen it if needed.

**Closed by jmmargo** 2024-08-12 21:22 UTC
