### ISSUE TITLE
Create a UI Using SAPUI5 Freestyle

### ISSUE THREAD

**Issue by SamratChakraborty** [sap-tutorials/Tutorials#23833] opened 2024-12-09 05:55 UTC
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-freestyle-sapui5.html
--------------------------

In this tutorial almost all of functionalities are deprecated when someone follow this tutorial in 2024 or later, specially when it's comes about beginners like me definitely they will face difficulty and it is not just about this tutorial but many things are deprecated and are not updated.

**Comment by rbrainey** [comment] 2024-12-09 15:13
Thanks for your feedback. As this is almost an exact duplicate of #23832 , I will close this. You can refer to that issue to follow our progress to a resolution.

**Closed by rbrainey** 2024-12-09 15:13 UTC
