### ISSUE TITLE
Design and Deploy Your First Integration Flow

### ISSUE THREAD

**Issue by I559299** [sap-tutorials/Tutorials#17997] opened 2022-01-12 06:00 UTC
Tutorials: https://developers.sap.com/tutorials/cp-starter-integration-cpi-design-iflow.html
--------------------------

Step 7: Connect request reply to receiver : sub-step:6 : After perform step6, unable to select the Products entity and shows the below error
<img width="838" alt="image" src="https://user-images.githubusercontent.com/95752943/149072200-146c1394-39bd-4c04-80ca-9e843b047d4e.png">

Scenario Labels:SCPTest-cloudin
Sprint Label: SCPTest-2201A
Landscape Label: trial3
Priority:High

In both region US and AP has the same issue

**Comment by I559299** [comment] 2022-01-13 08:31
Hi Colleagues,
Greetings!
This scenario is part of Global SAP D-kom Live Coding Space which is planned on 18th, 19th and 20th of Jan 2022. Currently this issue is the blocker to execute this scenario. So kindly request you to take it as very high priority and resolve this issue.

Regards,
Nidhi

**Comment by Karunaharan** [comment] 2022-01-13 08:46
Hi @I559299 
I'm already working on the issue. Will close the issue as soon as the issue is resolved.

**Comment by SamiLechner** [comment] 2022-01-14 09:10
Hi,
we have fixed the issue, the patch will be in the production landscapes by Monday evening. Please retest on Tuesday and give us feedback.
Sami

**Closed** 2022-01-17 05:08 UTC
Labels: SCPTest-trial2, SCPTest-cloudin, SCPTest-trial3, High-Prio, SCPTest-2201A

**Comment by Karunaharan** [comment] 2022-01-17 11:23
The issue is resolved.
