### ISSUE TITLE
Remote Table Replication - Design Time Object for Calculation View & Fulltext Index Replicas

### ISSUE THREAD

**Issue by ezennerGRE** [sap-tutorials/Tutorials#20751] opened 2022-11-23 03:28 UTC
Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-extend-09.html
--------------------------

This tutorial has been hugely helpful for simple table replication from an S/4HANA instance. We are running into two issues with the remote table replication. Could you please provide guidance on these common scenarios?

1) When attempting to deploy a calculation view with a replication table that is created using the demo, we receive the error "The file requires "db://S4HANA_BSEG_LCL" which is not provided by any file". I believe this is because following the tutorial creates the replication table via SQL without a design time object. From our experience a design time object is required for calculation view references in BAS. For example, we've created .hdbvirtualtable files with text definitions of "VIRTUAL TABLE "S4HANA_AUSP" AT "S4HANA"."<NULL>".SAPABAP1.AUSP". What would the corresponding file type and text definition be of the table replica created in step 3? Alternative, is there a way to reference the replica in a calculation view without a design time definition?

2) Replication of certain virtual tables (e.g. PRPS, LFM1) fail with "Fail: Cross-DB ATR doesn't support table with ASYNC fulltext index". We are not looking to replicate the full text index as it exists in our S/4HANA DB. Is there a way to replicate the raw data of these source tables? We're open to any workaround here.

Thanks in advance!
-Eric

**Comment by jmmargo** [comment] 2024-08-12 21:36
@thomashammerSAP I am reassigning this issue to you.  Please provide a response to the feedback.

**Comment by whome000** [comment] 2024-08-14 01:42
> ## Tutorials: https://developers.sap.com/tutorials/hana-cloud-mission-extend-09.html
> This tutorial has been hugely helpful for simple table replication from an S/4HANA instance. We are running into two issues with the remote table replication. Could you please provide guidance on these common scenarios?
> 
> 1. When attempting to deploy a calculation view with a replication table that is created using the demo, we receive the error "The file requires "db://S4HANA_BSEG_LCL" which is not provided by any file". I believe this is because following the tutorial creates the replication table via SQL without a design time object. From our experience a design time object is required for calculation view references in BAS. For example, we've created .hdbvirtualtable files with text definitions of "VIRTUAL TABLE "S4HANA_AUSP" AT "S4HANA"."".SAPABAP1.AUSP". What would the corresponding file type and text definition be of the table replica created in step 3? Alternative, is there a way to reference the replica in a calculation view without a design time definition?
> 2. Replication of certain virtual tables (e.g. PRPS, LFM1) fail with "Fail: Cross-DB ATR doesn't support table with ASYNC fulltext index". We are not looking to replicate the full text index as it exists in our S/4HANA DB. Is there a way to replicate the raw data of these source tables? We're open to any workaround here.
> 
> Thanks in advance! -Eric

Sorry for the belated reply.

#1. We only support replicating physical objects and do not support virtual tables from the source system. To overcome this, you can try to create one manually in the target schema with the same name. Hopefully this can resolve the issue.

#2. The fulltext index error was due to the difference of how they are implemented between the 2 systems. This needed a migration logic built into the replication. The issue is resolved now and requires an upgrade to the following versions HANA 2.0 Rev72+, Rev67.03+, Rev59.10+ (+ means 'or higher' for the mentioned SPS)

Best regards,
Tae-Suk Son
SAP HANA Product Management

**Closed** 2024-08-14 13:57 UTC
