### ISSUE TITLE
Connect SAP Continuous Integration and Delivery with Your Corporate Git

### ISSUE THREAD

**Issue by seVladimirs** [sap-tutorials/Tutorials#18106] opened 2022-02-10 11:18 UTC
Tutorials: https://developers.sap.com/tutorials/cicd-corporate-git.html
--------------------------

Step 1.6 - 1.8 says you need to click on your identity provider and then find your user. I think SAP BTP cockpit is changed and now it is not possible (there is no hyperlink anymore, see screenshot below), instead you need to go to Security -> Users.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/9819889/153396611-d5cc9b1e-4261-4c62-9ccd-5a49ff71f291.png">

**Comment by iwonahahn** [comment] 2022-05-20 11:57
Hi @seVladimirs,

As you can see in the mentioned pull request the issue is resolved and I will close this issue. 

Best regards,
Iwona

**Closed by iwonahahn** 2022-05-20 11:57 UTC
