### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by miroslavpetrovic** [sap-tutorials/Tutorials#18515] opened 2022-06-13 15:49 UTC
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

Hi Colleagues,

I am getting an error message while trying to create Deploy MTA Archive.

Error I am getting:
[OPERATION.log](https://github.com/sap-tutorials/Tutorials/files/8892558/OPERATION.log)

Creating service "sap-btp-sapui5-xsuaa-srv" from MTA resource "sap-btp-sapui5-uaa"...
Service operation failed: Controller operation failed: 404 Updating service "sap-btp-sapui5-xsuaa-srv" failed: Not Found: Error creating service "sap-btp-sapui5-xsuaa-srv" from offering "xsuaa" and plan "application": Service plan application not found. 
Proceeding with automatic retry... (1 of 3 attempts left)
Creating service "sap-btp-sapui5-xsuaa-srv" from MTA resource "sap-btp-sapui5-uaa"...
Service operation failed: Controller operation failed: 404 Updating service "sap-btp-sapui5-xsuaa-srv" failed: Not Found: Error creating service "sap-btp-sapui5-xsuaa-srv" from offering "xsuaa" and plan "application": Service plan application not found. 

I attached the Operation.log as well.

Best,

MIro

**Comment by cjbernal** [comment] 2022-06-14 16:24
Hi Miro,

Sorry to see that you are having an issue. I will reach out to my deployment colleagues to see who can assist you best. 

Kind regards,
Conrad

**Comment by longieirl** [comment] 2022-06-14 19:58
Hi,
Please ensure the following;
You are subscribed to the SAP Launchpad Service, follow this [tutorial](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-getting-started.html) for more information.
If the referenced services are not available in Service Marketplace, please select Entitlements from the root of your subacacount, select Configure Entitlements, locate the required service, create it, save it and then return to the Service Marketplace to add the required service to your subaccount.
Please revert back to us if this does not resolve your issue.
John

**Comment by boyan-velinov** [comment] 2022-06-15 11:07
Hi,

From MTA deploy service side, I can tell that the problem is returned by Service broker of CF itself. Beleive the same problem will appear if manually, outside of the MTA. Most probably, the issue is related to missing entitlements for service offering xsuaa and/or plan application.
When have  issues for MTA deployment in CF, you can checkout the troubleshooting:
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/3530af7ff2b449fbbc591dd3e2c0d151.html
or directly guided answers:
https://ga.support.sap.com/dtp/viewer/index.html#/tree/2798

Best Regads,
Boyan

**Comment by MichaelCzcz** [comment] 2023-02-21 14:20
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.

**Closed by MichaelCzcz** 2023-02-21 14:20 UTC
