### ISSUE TITLE
Tutorial Page btp-app-ext-service-intro.md Issue. PROD

### ISSUE THREAD

**Issue by DevRelations2** [sap-tutorials/Tutorials#20788] opened 2022-12-06 17:48 UTC
Tutorial issue found: [https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/btp-app-ext-service-intro/btp-app-ext-service-intro.md](https://github.com/sap-tutorials/Tutorials/blob/master/tutorials/btp-app-ext-service-intro/btp-app-ext-service-intro.md) contains invalid tags. Even though your tutorial was created, the invalid tags listed below were disregarded. Please double-check the following tags:
- products>sap-s-4hana-cloud

 Affected server: PROD

**Comment by manjuX** [comment] 2022-12-14 09:36
Hello,

How can we find the correct tags to use? I could not find it in the tutorials creation guide or the style guide.

Best regards,
Manju

**Comment by MichaelCzcz** [comment] 2022-12-14 10:19
There is a list with all the primary tags in IMS. Unfortunately yours is missing there.
In your case the issue is that the tag's name space has been changed from products to software-product over a year ago.
The correct primary tag is software-product>sap-s-4hana-cloud

**Comment by manjuX** [comment] 2022-12-14 11:36
Thanks Michael, I'll update it.

**Comment by manjuX** [comment] 2023-02-09 10:50
Closing as it was updated.

**Closed by manjuX** 2023-02-09 10:50 UTC
