### ISSUE TITLE
Create a Dev Space for SAP Fiori Apps

### ISSUE THREAD

**Issue by jubo0001** [sap-tutorials/Tutorials#22953] opened 2023-03-27 14:03 UTC
Tutorials: https://developers.sap.com/tutorials/appstudio-devspace-fiori-create.html
--------------------------
I think there is a step missing in the tutorial between "Creating the Dev Space" and "Debug Your SAPUI5 App with SAP Business Application Studio". What kind of FIORI project do you create inbetween? There are severl templates that one can choose

**Comment by raz-korn** [comment] 2023-04-06 08:24
Hi @jubo0001 ,

Please provide more details - There is no "Debug Your SAPUI5 App with SAP Business Application Studio" step in this tutorial.

Regards - Raz

**Comment by jubo0001** [comment] 2023-04-06 12:12
Hi,

Thank you for your reply.

When I go from this tutorial to the next tutorial I see this:

***@***.***


The next tutorial I see is this one:

***@***.***


Should this not be the logical successor of the first tutorial?

Regards,

Jürgen




Von: Raz Korn ***@***.***>
Gesendet: Donnerstag, 6. April 2023 10:25
An: sap-tutorials/Tutorials ***@***.***>
Cc: Jürgen Bottler ***@***.***>; Mention ***@***.***>
Betreff: Re: [sap-tutorials/Tutorials] Create a Dev Space for SAP Fiori Apps (Issue #22953)


Hi @jubo0001<https://github.com/jubo0001> ,

Please provide more details - There is no "Debug Your SAPUI5 App with SAP Business Application Studio" step in this tutorial.

Regards - Raz

**Comment by jubo0001** [comment] 2023-04-06 12:14
You can also see the sequence here:

***@***.***

Von: Raz Korn ***@***.***>
Gesendet: Donnerstag, 6. April 2023 10:25
An: sap-tutorials/Tutorials ***@***.***>
Cc: Jürgen Bottler ***@***.***>; Mention ***@***.***>
Betreff: Re: [sap-tutorials/Tutorials] Create a Dev Space for SAP Fiori Apps (Issue #22953)


Hi @jubo0001<https://github.com/jubo0001> ,

Please provide more details - There is no "Debug Your SAPUI5 App with SAP Business Application Studio" step in this tutorial.

Regards - Raz

**Comment by jubo0001** [comment] 2023-04-11 06:58
Hi Raz,

Please check the sequence of the tutorials in this mission:
https://developers.sap.com/group.sapui5-cf-bas.html

Step 3 is "Create a Dev Space for SAP Fiori Apps"

Step 4 is "Debug your SAPUI5 App with SAP Business Application Studio"

For me it seems that there is s.th. missing inbetween.

Regards,

Jürgen

**Comment by raz-korn** [comment] 2023-04-16 12:24
Hi @jubo0001 ,

I apologize for the late reply - holiday season here :-)
@cjbernal: Jürgen seems to be correct that a tutorial is mossing. Can you assist?

Regards - Raz

**Comment by cjbernal** [comment] 2023-04-17 17:14
Hi @jubo0001 and @raz-korn, I've discussed this with the tutorials team before and was unable to turn up the missing tutorial as I was not the one that created the group -- so I was not familiar with its contents. I typically just provide ad-hoc updates as requested by the product team. But I will follow up with them to see if they can dig up what was there previously. Please stay tuned.

**Comment by jmmargo** [comment] 2024-08-13 14:51
@cjbernal is this issue resolved, or was there an update?

**Comment by cjbernal** [comment] 2024-08-15 14:17
@jmmargo This issue was resolved. There is an internal mail between the SAP colleagues in this ticket, ourselves included, on April 20, 2023 where we confirmed the required changes were made. Subject: "Regarding tutorial issue #20784" -- because it was affecting multiple tutorials.

**Comment by jmmargo** [comment] 2024-08-15 19:31
Thank you @cjbernal I will close the issue accordingly.

**Closed by jmmargo** 2024-08-15 19:31 UTC
