### ISSUE TITLE
Build Luigi App with React

### ISSUE THREAD

**Issue by tobiaswild** [sap-tutorials/Tutorials#18274] opened 2022-03-28 07:14 UTC
Tutorials: https://developers.sap.com/tutorials/luigi-app-react.html
--------------------------

Step 9
When I try to run the application, the browser just shows me a white canvas and in the console are three errors, but I don't have any idea how to fix them and also couldn't find any fix on the Internet. 
What can I do about this?

![Image](https://user-images.githubusercontent.com/46871747/160345348-ea7bbcc1-bdfc-4ea1-a9c7-e5501e709ba1.png)

**Comment by alexandra-simeonova** [comment] 2022-03-31 15:03
Hi Tobias,

I'm not sure what the error is, but I will ask the Luigi developers. Maybe you could try to compare your code with the one in the finished example repository https://github.com/SAP-samples/luigi-micro-frontend-application , in case something was pasted wrong?

**Comment by tobiaswild** [comment] 2022-04-01 06:20
Hey Alexandra,

Thanks a lot for your help. I don't know where I made the mistake, but after copying the sample repo, everything works.

**Comment by alexandra-simeonova** [comment] 2022-04-04 13:34
Hi, 
because the issue is resolved I will close this for now, but feel free to reopen if you have other questions. Thank you!

**Closed by alexandra-simeonova** 2022-04-04 13:34 UTC
