### ISSUE TITLE
Set Up Integration Suite Trial

### ISSUE THREAD

**Issue by Venkatpicons** [sap-tutorials/Tutorials#18609] opened 2022-07-12 09:28 UTC
Tutorials: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
--------------------------

Issue: When we are trying to start the booster "Enable Integration Suite", creating service instances is getting failed.

Steps to reproduce: 
In tutorial:  https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html

At step:4 Automatically assign roles and create service instances using Booster : 
Step 6 - After choosing finish, In progress popup window its showing "creating services instances" in failed status. 

Observation:
After the above step, navigated to "instances and subscriptions" where we can find the successfully created instances though its showing the failed error in the above mentioned step.

Solution: Progress popup window should show the status as "Done" for Creating Service Instances.

Please find the attached screenshot for reference.

Kindly look into this issue.

Labels to be added:
Scenario Label:SCPTest-cloudin
Sprint label: SCPTest-2207A
Landscape label:trail2
Priority:High

Kind regards
Venkat
![US Region_Booster Issue](https://user-images.githubusercontent.com/60374957/178457969-c222e212-d6a9-4f03-91ae-41fdd0a97118.JPG)
![Successfull instances](https://user-images.githubusercontent.com/60374957/178458413-43ffa731-ae5b-4233-a45f-d0151f241372.JPG)

**Comment by Karunaharan** [comment] 2022-08-30 08:00
@Venkatpicons  - apologies for the delay. The issue is fixed now.

**Closed by Karunaharan** 2022-08-30 08:00 UTC
Labels: SCPTest-trial2, SCPTest-cloudin, High-Prio, SCPTest-2207A
