### ISSUE TITLE
Issue in Set Up for the Mobile Development Kit (MDK) in US region

### ISSUE THREAD

**Issue by Akashbm964** [sap-tutorials/Tutorials#23814] opened 2024-11-12 11:19 UTC
Hi Colleagues,

We are testing Starter scenarios for the November Month cycle.

Tutorial link : https://developers.sap.com/group.mobile-dev-kit-setup.html
Trail account link : https://cockpit.hanatrial.ondemand.com/trial/#/home/trial

Here, at last step after successfully deploying & opening the application we are getting error as Internal Server Error

https://github.com/user-attachments/assets/7a3b1344-c4e8-448b-83a5-512625af90de

Thanks & regards,
Akash

**Comment by jmmargo** [comment] 2024-11-12 14:46
@jitendrakansal can you please respond to this user's feedback?  Thank you.

**Comment by jitendrakansal** [comment] 2024-11-12 14:50
@Akashbm964 this is currently a known issue. We have already identified the root cause and planning to patch a fix soon.

In meanwhile, please follow below workaround:

- Open **WebApplicationFactory** folder in SAP Business Application Studio (if you do not see it in the project explorer, make sure to open explorer at Projects folder level. File>Open Folder >Projects) 
- Right click **mta.yaml** and click **Build MTA Project**
- Right click the **.mtar** file in **mta_archives** and click **Deploy MTA Archive**.
- Once the deploy task is completed, access the MDK web app.

**Comment by Akashbm964** [comment] 2024-11-13 04:47
Hi @jitendrakansal 

I tried the workaround you had provided and it worked.

After successful deployment of **.mtar** file , DemoSampleApp got displayed.

![image](https://github.com/user-attachments/assets/fc5bc00a-b33b-4f96-a580-1b3d34d789ed)

![image](https://github.com/user-attachments/assets/2a05650c-e634-46cb-9619-1affa7771a6b)

Thanks & regards,
Akash

**Comment by jmmargo** [comment] 2024-11-13 14:42
@jitendrakansal can we close this issue?

**Comment by jitendrakansal** [comment] 2024-11-13 15:52
@Akashbm964 We released a patch in the editor fixing the original issue. Please redeploy from BAS and test again.
@jmmargo Closing this issue as solution and fix has been provided.

**Closed by jitendrakansal** 2024-11-13 15:52 UTC
